dist: trusty
sudo: required

# Not technically required but suppresses 'Ruby' in Job status message.
language: java

git:
  depth: 1
os:
  - linux
env:
  - V=0.28.0
before_install:
  # Borrowed from rules_scala
  - |
    sysctl kernel.unprivileged_userns_clone=1
    sudo apt-get update -q
    sudo apt-get install libxml2-utils -y
    OS=linux
    if [[ $V =~ .*rc[0-9]+.* ]]; then
      PRE_RC=$(expr "$V" : '\([0-9.]*\)rc.*')
      RC_PRC=$(expr "$V" : '[0-9.]*\(rc.*\)')
      URL="https://storage.googleapis.com/bazel/${PRE_RC}/${RC_PRC}/bazel-${V}-installer-${OS}-x86_64.sh"
    else
      URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    fi
    wget -nv -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
  - cat .bazelrc.travis >> .bazelrc
script:
  - ./test/run_all_tests.sh ci
after_success:
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" == true ] && [ -n "$TRAVIS_TAG" ]; then
      echo "$PGP_SECRET" | base64 --decode | gpg --import
      bash scripts/publish.sh
    else
      echo "Skipped publishing."
      echo "Travis Tag: $TRAVIS_TAG"
      echo "TRAVIS_SECURE_ENV_VARS: $TRAVIS_SECURE_ENV_VARS"
    fi
